server:
  port: 4010

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005 #/api/auth will be routed here for the auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1 # Will strip the `api` part becuase authcontroller listens at `/auth`
        - id: user-service-route
          uri: http://user-service:4000 #/api/users will be routed here for the users-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1 # Will strip the `api` part becuase authcontroller listens at `/users`
            - JwtValidation # Must match Srping naming convention. Request will passed to <filterName>GatewayFilterFactory


logging:
  level: 
    root: debug
    org.springframework: debug
    org.hibernate: warn


