spring:
  application:
    name: user-service

#   h2:
#     console:
#       # If needed to access de /h2-console please change this to true and add the spring.security.enabled: false (in order to by pass it)
#       enabled: false
#       path: /h2-console
#   # security:
#   #   enabled: false
#   datasource:
#     url: jdbc:h2:mem:testdb
#     driver-class-name: org.h2.Driver
#     username: developer
#     password: password
#
jpa:
  # database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update
#   sql:
#     init:
#       mode: always
# jwt: 
#   secret: ${JWT_SECRET}

server:
  port: 4000

logging:
  level:
    root: info

