version: '3.8'

services:
  api-guard:
    container_name: api-guard
    image: api-guard:latest
    env_file:
      - .env
    networks:
      - internal  
    ports:
      - "4010:4010"
networks:
  internal:
    external: true
    name: internal
